id: P7E8C6E8C
initial_creation_type: input
source_metadata:
  title: Kachöpa Series
  language: en
  description: Prayers and Practices
  volume:
    1f0e153eaa494a048614f139df09c7fa:
      title: Raising the Windhorse
      parent: Prayers and Practices
created_at: '2022-03-01T00:09:28.225358'
last_modified_at: '2022-03-01T00:09:28.225364'
